[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jadeai"
version = "0.0.0"
description = "JadeAI 2.0 local agentic stack"
requires-python = ">=3.11"

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q"
