openapi: 3.0.0
info:
  title: JadeAI HID API
  version: "1.0.0"
  description: REST API for Bluetooth HID keyboard/mouse control

servers:
  - url: http://localhost:5001

paths:
  /hid/text:
    post:
      summary: Type text on the HID keyboard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Hello world"
      responses:
        '204':
          description: Text sent successfully

  /hid/move:
    post:
      summary: Move the mouse cursor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                x:
                  type: integer
                  example: 10
                y:
                  type: integer
                  example: -5
      responses:
        '204':
          description: Mouse moved successfully

  /hid/click:
    post:
      summary: Simulate a mouse click
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                button:
                  type: string
                  enum: [left, right, middle]
                  example: "left"
      responses:
        '204':
          description: Click event sent

  /hid/status:
    get:
      summary: Check Bluetooth status
      responses:
        '200':
          description: Status response
          content:
            application/json:
              schema:
                type: object
                properties:
                  powered:
                    type: boolean
                  discoverable:
                    type: boolean

  /hid/disconnect:
    post:
      summary: Disconnect all paired devices
      responses:
        '204':
          description: Devices disconnected

  /hid/health:
    get:
      summary: Health check
      responses:
        '200':
          description: Health OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
