# Bluetooth Component Configuration
version: "1.0.0"
name: "jade-bluetooth"
description: "Jade Bluetooth Management Component"

# Version requirements
required_versions:
  system: "1.0.0"
  bluez: "5.50"

# Required packages
packages:
  - name: "bluez"
    required: true
  - name: "bluez-tools"
    required: true
  - name: "bluetooth"
    required: true
  - name: "rfkill"
    required: true

# Required directories
directories:
  - path: "/etc/jade/bluetooth"
    mode: "755"
    required: true
  - path: "/var/log/jade/bluetooth"
    mode: "755"
    required: true

# Status file location
status:
  file: "/etc/jade/bluetooth/status"
  mode: "644"

# Deployment settings
deployment:
  backup:
    enabled: true
    location: "/opt/jade/backups/bluetooth"
  rollback:
    enabled: true
    keep_versions: 3
  post_deploy:
    test_enabled: true
    test_timeout: 300

# Service configuration
service:
  name: "bluetooth"
  display_name: "JadeAI Bluetooth"
  config_file: "/etc/bluetooth/main.conf"
  systemd_unit: "bluetooth.service"
  discoverable_timeout: 0
  discoverable: true
  auto_enable: true

# Docker settings
docker:
  compose_file: "docker-compose.yml"
  network: "jade-network"
  components:
    - name: "jade-bluetooth"
      image: "jade-bluetooth:$JADE_BLUETOOTH_VERSION"
      privileged: true
      network_mode: "host"
      volumes:
        - "/var/run/dbus:/var/run/dbus"
        - "/etc/bluetooth:/etc/bluetooth"
        - "/var/log/jade/bluetooth:/var/log/bluetooth"
      environment:
        - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket"
