# HID Component Configuration
version: "1.0.0"
name: "jade-hid"
description: "Jade HID (Human Interface Device) Management Component"

# Version requirements
required_versions:
  system: "1.0.0"
  udev: "245"

# Required packages
packages:
  - name: "udev"
    required: true
  - name: "libhidapi-dev"
    required: true
  - name: "libusb-1.0-0-dev"
    required: true
  - name: "libudev-dev"
    required: true
  - name: "python3-hid"
    required: true
  - name: "python3-usb"
    required: true

# Required directories
directories:
  - path: "/etc/jade/hid"
    mode: "755"
    required: true
  - path: "/var/log/jade/hid"
    mode: "755"
    required: true
  - path: "/opt/jade/hid"
    mode: "755"
    required: true
  - path: "/etc/udev/rules.d"
    mode: "755"
    required: true

# Status file location
status:
  file: "/etc/jade/hid/status"
  mode: "644"

# Deployment settings
deployment:
  backup:
    enabled: true
    location: "/opt/jade/backups/hid"
  rollback:
    enabled: true
    keep_versions: 3
  post_deploy:
    test_enabled: true
    test_timeout: 300

# HID configuration
hid:
  udev_rules:
    file: "/etc/udev/rules.d/99-jade-hid.rules"
    mode: "644"
  devices:
    - type: "keyboard"
      required: true
      vendor_id: "*"
      product_id: "*"
      permissions: "666"
    - type: "mouse"
      required: true
      vendor_id: "*"
      product_id: "*"
      permissions: "666"
    - type: "joystick"
      required: false
      vendor_id: "*"
      product_id: "*"
      permissions: "666"

# Docker settings
docker:
  compose_file: "docker-compose.yml"
  network: "jade-network"
  components:
    - name: "jade-hid"
      image: "jade-hid:${version}"
      privileged: true
      volumes:
        - "/dev/bus/usb:/dev/bus/usb"
        - "/run/udev:/run/udev:ro"
        - "/var/log/jade/hid:/var/log/hid"
      devices:
        - "/dev/input:/dev/input"
      environment:
        - "UDEV_RULES_PATH=/etc/udev/rules.d"
      ports:
        - "8556:8556"  # HID API
