# Web Admin Component Configuration
version: "1.0.0"
name: "jade-web-admin"
description: "Jade Web Administration Interface"

# Version requirements
required_versions:
  system: "1.0.0"
  nginx: "1.18.0"

# Required packages
packages:
  - name: "nginx"
    required: true
  - name: "python3-flask"
    required: true
  - name: "python3-gunicorn"
    required: true
  - name: "python3-requests"
    required: true
  - name: "python3-websockets"
    required: true
  - name: "python3-aiohttp"
    required: true
  - name: "certbot"
    required: true
  - name: "python3-certbot-nginx"
    required: true

# Required directories
directories:
  - path: "/etc/jade/web-admin"
    mode: "755"
    required: true
  - path: "/var/log/jade/web-admin"
    mode: "755"
    required: true
  - path: "/var/www/jade-admin"
    mode: "755"
    required: true
  - path: "/etc/nginx/sites-available"
    mode: "755"
    required: true
  - path: "/etc/nginx/sites-enabled"
    mode: "755"
    required: true

# Status file location
status:
  file: "/etc/jade/web-admin/status"
  mode: "644"

# Deployment settings
deployment:
  backup:
    enabled: true
    location: "/opt/jade/backups/web-admin"
  rollback:
    enabled: true
    keep_versions: 3
  post_deploy:
    test_enabled: true
    test_timeout: 300

# Web server configuration
web:
  nginx:
    config_file: "/etc/nginx/sites-available/jade-admin"
    server_name: "admin.jade.local"
    port: 8080
    ssl:
      enabled: true
      cert_path: "/etc/letsencrypt/live/admin.jade.local/fullchain.pem"
      key_path: "/etc/letsencrypt/live/admin.jade.local/privkey.pem"
  gunicorn:
    workers: 4
    bind: "unix:/run/jade-admin.sock"
    timeout: 120
  api:
    port: 8081
    endpoints:
      - path: "/api/v1/system"
        methods: ["GET", "POST"]
        auth_required: true
      - path: "/api/v1/network"
        methods: ["GET", "POST"]
        auth_required: true
      - path: "/api/v1/bluetooth"
        methods: ["GET", "POST"]
        auth_required: true
      - path: "/api/v1/video"
        methods: ["GET", "POST"]
        auth_required: true
      - path: "/api/v1/hid"
        methods: ["GET", "POST"]
        auth_required: true
  auth:
    session_timeout: 3600
    max_attempts: 3
    lockout_time: 300

# Docker settings
docker:
  compose_file: "docker-compose.yml"
  network: "jade-network"
  components:
    - name: "jade-web-admin"
      image: "jade-web-admin:${version}"
      volumes:
        - "/etc/nginx:/etc/nginx"
        - "/var/www/jade-admin:/var/www/jade-admin"
        - "/var/log/jade/web-admin:/var/log/web-admin"
        - "/etc/letsencrypt:/etc/letsencrypt"
        - "/run:/run"
      ports:
        - "8080:8080"
        - "8081:8081"
      environment:
        - "NGINX_SERVER_NAME=admin.jade.local"
        - "API_PORT=8081"
        - "SSL_ENABLED=true"
      depends_on:
        - "jade-system"
        - "jade-bluetooth"
        - "jade-video"
        - "jade-hid"
        - "jade-wifi"
