# WiFi Component Configuration
version: "1.0.0"
name: "jade-wifi"
description: "Jade WiFi Management Component"

# Version requirements
required_versions:
  system: "1.0.0"
  wpa_supplicant: "2.9"

# Required packages
packages:
  - name: "wpasupplicant"
    required: true
  - name: "wireless-tools"
    required: true
  - name: "iw"
    required: true
  - name: "hostapd"
    required: true
  - name: "dnsmasq"
    required: true
  - name: "netplan.io"
    required: true
  - name: "bridge-utils"
    required: true

# Required directories
directories:
  - path: "/etc/jade/wifi"
    mode: "755"
    required: true
  - path: "/var/log/jade/wifi"
    mode: "755"
    required: true
  - path: "/etc/netplan"
    mode: "755"
    required: true
  - path: "/etc/hostapd"
    mode: "755"
    required: true
  - path: "/etc/dnsmasq.d"
    mode: "755"
    required: true

# Status file location
status:
  file: "/etc/jade/wifi/status"
  mode: "644"

# Deployment settings
deployment:
  backup:
    enabled: true
    location: "/opt/jade/backups/wifi"
  rollback:
    enabled: true
    keep_versions: 3
  post_deploy:
    test_enabled: true
    test_timeout: 300

# WiFi configuration
wifi:
  netplan:
    file: "/etc/netplan/99-jade-wifi.yaml"
    mode: "600"
  hostapd:
    file: "/etc/hostapd/hostapd.conf"
    mode: "600"
  dnsmasq:
    file: "/etc/dnsmasq.d/jade-wifi"
    mode: "644"
  wpa_supplicant:
    file: "/etc/wpa_supplicant/wpa_supplicant.conf"
    mode: "600"
  interfaces:
    client:
      name: "wlan0"
      mode: "managed"
      dhcp: true
      scan_interval: 30
    ap:
      name: "wlan1"
      mode: "ap"
      ssid: "JadeAI"
      password: "jade1234"
      channel: 6
      band: "2.4GHz"
      ip: "192.168.4.1"
      netmask: "255.255.255.0"
      dhcp:
        start: "192.168.4.100"
        end: "192.168.4.200"
        lease: "12h"

# Docker settings
docker:
  compose_file: "docker-compose.yml"
  network: "jade-network"
  components:
    - name: "jade-wifi"
      image: "jade-wifi:${version}"
      privileged: true
      network_mode: "host"
      volumes:
        - "/etc/netplan:/etc/netplan"
        - "/etc/hostapd:/etc/hostapd"
        - "/etc/dnsmasq.d:/etc/dnsmasq.d"
        - "/etc/wpa_supplicant:/etc/wpa_supplicant"
        - "/var/log/jade/wifi:/var/log/wifi"
      environment:
        - "WIFI_CLIENT_INTERFACE=wlan0"
        - "WIFI_AP_INTERFACE=wlan1"
      cap_add:
        - "NET_ADMIN"
        - "SYS_MODULE"
