mode: ${JADEAI_HID_MODE:bluetooth}
device_name: ${JADEAI_HID_DEVICE_NAME:JadeAI HID}
ble_adapter: ${JADEAI_HID_BLE_ADAPTER:hci0}
rate_limit:
  keypress_per_second: 12
  pointer_updates_per_second: 60
